name: my new workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    # run on github hosted ubuntu runner
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Create virtual environment
        run: python -m venv venv
      
      # Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          source venv/bin/activate
          pip install -r starter-app2/requirements.txt
          pytest -v
          flake8 . --max-line-length=100 --exclude=venv

